# Generated by Django 4.0.4 on 2022-04-19 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.TextField(default=datetime.datetime(2022, 4, 19, 22, 35, 26, 482617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
